import Head from 'next/head'

export default function Home() {
  return (
    <div className='' >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to Next.js!
        </h1>

        <p>
          Get started by editing <code>pages/index.js</code>
        </p>
      </main>

      <footer >

      </footer>
    </div >
  )
}
